import { download } from './utils.js';


export function graphToPs1(graph){
const order = graph.topoOrder();
const inbound = graph.inboundMap();
let out = [
'# --- Auto-generated by PowerFlow (VanillaJS) ---',
`# Date: ${new Date().toISOString()}`,
''
];


for(const id of order){
const n = graph.nodes.get(id);
out.push(`# Node: ${n.name} [${n.id}]`);


// bind inputs ($input → $nodeId_input)
const inboundList = inbound.get(id) || [];
if (inboundList.length){
inboundList.forEach(m=> out.push(`$${id}_${m.in} = ${m.from}`));
} else {
Object.keys(n.inputs).forEach(inp=> out.push(`$${id}_${inp} = $null`));
}


let script = n.script;
Object.keys(n.inputs).forEach(inp=> { script = script.replaceAll(`$${inp}`, `$${id}_${inp}`); });
Object.keys(n.outputs).forEach(op=> { script = script.replaceAll(`$${op}`, `$${id}_${op}`); });


out.push(script.trim(), '');
}
return out.join('\n');
}


export function exportPs1(graph){
download('workflow.ps1', graphToPs1(graph));
}